import React, { useState } from 'react';
import {
  UploadCloud,
  FileCheck,
  AlertTriangle,
  FolderKanban,
  CheckSquare,
  Users,
  FileText,
  Zap,
  Activity,
  X,
  Check,
} from 'lucide-react';
import { Modal } from '../common/Modal';

interface ImportPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => Promise<void>;
  counts: Record<string, number>;
  fileName?: string;
  sourceClient?: string;
  exportedAt?: string;
}

export const ImportPreviewModal: React.FC<ImportPreviewModalProps> = ({
  isOpen,
  onClose,
  onConfirm,
  counts,
  fileName,
  sourceClient,
  exportedAt,
}) => {
  const [isApplying, setIsApplying] = useState(false);
  const [hasConfirmedCheckbox, setHasConfirmedCheckbox] = useState(false);

  const handleApply = async () => {
    setIsApplying(true);
    try {
      await onConfirm();
      onClose();
    } finally {
      setIsApplying(false);
    }
  };

  const statItems = [
    { label: 'Projects', count: counts.projects ?? 0, icon: FolderKanban, color: 'text-brand-500' },
    { label: 'Tasks', count: counts.tasks ?? 0, icon: CheckSquare, color: 'text-emerald-500' },
    { label: 'Members', count: counts.members ?? 0, icon: Users, color: 'text-indigo-500' },
    { label: 'Documents', count: counts.documents ?? 0, icon: FileText, color: 'text-amber-500' },
    { label: 'Automations', count: counts.automations ?? 0, icon: Zap, color: 'text-sky-500' },
    { label: 'Activities', count: counts.activities ?? 0, icon: Activity, color: 'text-purple-500' },
  ];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Verify & Preview Workspace Import"
      description="Review the verified dataset structure before applying replacement."
      maxWidth="md"
    >
      <div className="space-y-5 text-xs">
        {/* Source metadata card */}
        <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-slate-400 font-medium">Source File</span>
            <span className="font-mono text-slate-800 dark:text-slate-200 font-semibold truncate max-w-[200px]">
              {fileName || 'nexus-workspace.json'}
            </span>
          </div>
          {sourceClient && (
            <div className="flex items-center justify-between">
              <span className="text-slate-400">Generated by</span>
              <span className="text-slate-700 dark:text-slate-300 font-medium">{sourceClient}</span>
            </div>
          )}
          {exportedAt && (
            <div className="flex items-center justify-between">
              <span className="text-slate-400">Export Timestamp</span>
              <span className="font-mono text-slate-600 dark:text-slate-400">
                {new Date(exportedAt).toLocaleString()}
              </span>
            </div>
          )}
        </div>

        {/* Entity counts breakdown */}
        <div>
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2.5 block">
            Validated Entity Counts
          </span>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
            {statItems.map((item) => {
              const Icon = item.icon;
              return (
                <div
                  key={item.label}
                  className="p-3 rounded-xl bg-white dark:bg-[#151c2e] border border-slate-200 dark:border-slate-800 flex items-center justify-between"
                >
                  <div className="flex items-center gap-2">
                    <Icon className={`w-4 h-4 ${item.color}`} />
                    <span className="text-slate-600 dark:text-slate-300 font-medium">{item.label}</span>
                  </div>
                  <span className="font-bold font-mono text-slate-900 dark:text-white">
                    {item.count}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Destructive replacement caution notice */}
        <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-700 dark:text-amber-300 flex items-start gap-2.5">
          <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
          <div className="leading-relaxed">
            <p className="font-bold">Complete Workspace Replacement</p>
            <p className="text-[11px] mt-0.5 text-amber-600/90 dark:text-amber-400/90">
              Applying this import will overwrite the current active workspace, including tasks, custom projects, documents, and automation rules.
            </p>
          </div>
        </div>

        {/* Explicit confirmation checkbox */}
        <label className="flex items-start gap-2.5 p-2 rounded-lg cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-900/40 select-none">
          <input
            type="checkbox"
            checked={hasConfirmedCheckbox}
            onChange={(e) => setHasConfirmedCheckbox(e.target.checked)}
            className="rounded text-brand-600 focus:ring-brand-500 mt-0.5"
          />
          <span className="text-slate-700 dark:text-slate-300 text-[11px]">
            I understand that my current local workspace data will be replaced with the imported dataset.
          </span>
        </label>

        {/* Modal actions */}
        <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-slate-100 dark:border-slate-800">
          <button
            type="button"
            onClick={onClose}
            disabled={isApplying}
            className="px-4 py-2 rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 font-medium transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleApply}
            disabled={!hasConfirmedCheckbox || isApplying}
            className={`flex items-center gap-1.5 px-5 py-2 rounded-xl font-semibold text-white shadow-xs transition-all ${
              hasConfirmedCheckbox && !isApplying
                ? 'bg-brand-600 hover:bg-brand-500 hover:scale-[1.02] active:scale-[0.98]'
                : 'bg-slate-300 dark:bg-slate-800 text-slate-500 cursor-not-allowed shadow-none'
            }`}
          >
            {isApplying ? (
              <span>Restoring Workspace...</span>
            ) : (
              <>
                <Check className="w-4 h-4" />
                <span>Replace Workspace with Import</span>
              </>
            )}
          </button>
        </div>
      </div>
    </Modal>
  );
};
